workflows:
  android-build:
    name: Android build
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: production
      flutter: none
      xcode: latest
      cocoapods: default
      node: stable
    scripts:
      - npm install
      - npm run android --if-present
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - louis.supiot111@gmail.com
          
