workflows:
  android-build:
    name: Android build
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: production
      node: stable
      # Pas besoin de flutter ni xcode pour Android React Native
    scripts:
      - npm install
      - npx react-native run-android --variant=release
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - louis.supiot111@gmail.com
